stages:
  - validate
  - plan

variables:
  TF_WORKDIR: "terraform/environments/dev"

validate:
  stage: validate
  image: 
    name: hashicorp/terraform:1.7.5
    entrypoint: [""]
  script:
    - cd "$TF_WORKDIR"
    - terraform init -backend=false
    - terraform fmt -check -recursive
    - terraform validate

plan:
  stage: plan
  image:
    name: hashicorp/terraform:1.7.5
    entrypoint: [""]
  script:
    - cd "$TF_WORKDIR"
    - terraform init
    - terraform plan -out=tfplan -var-file="terraform.tfvars.example"
  artifacts:
    paths:
      - $TF_WORKDIR/tfplan
    expire_in: 7 days